FROM node:20-alpine AS builder
WORKDIR /app
COPY package.json /app/package.json
RUN npm install
COPY . /app
ENV NEXT_PUBLIC_API_BASE=http://104.238.128.128:8080
RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY --from=builder /app/package.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/next.config.js ./
EXPOSE 3000
CMD ["npx", "next", "start", "-H", "0.0.0.0", "-p", "3000"]
